// AUTO-GENERATED by scripts/generate-catalog.mjs — do not edit by hand.
import type { ComponentType } from 'react'
import AccordionBasic from '../../ui/src/components/accordion/examples/basic'
import AccordionCard from '../../ui/src/components/accordion/examples/card'
import AlertVariants from '../../ui/src/components/alert/examples/variants'
import AlertDialogBasic from '../../ui/src/components/alert-dialog/examples/basic'
import AlertDialogAsync from '../../ui/src/components/alert-dialog/examples/async'
import AreaChartBasic from '../../charts/src/components/area-chart/examples/basic'
import AreaChartStacked from '../../charts/src/components/area-chart/examples/stacked'
import AspectRatioBasic from '../../ui/src/components/aspect-ratio/examples/basic'
import AspectRatioRatios from '../../ui/src/components/aspect-ratio/examples/ratios'
import AudioPlayerBasic from '../../ui/src/components/audio-player/examples/basic'
import AudioPlayerCompact from '../../ui/src/components/audio-player/examples/compact'
import AutocompleteBasic from '../../ui/src/components/autocomplete/examples/basic'
import AvatarBasic from '../../ui/src/components/avatar/examples/basic'
import AvatarSizes from '../../ui/src/components/avatar/examples/sizes'
import AvatarGroup from '../../ui/src/components/avatar/examples/group'
import BadgeVariants from '../../ui/src/components/badge/examples/variants'
import BadgeWithIcon from '../../ui/src/components/badge/examples/with-icon'
import BarChartBasic from '../../charts/src/components/bar-chart/examples/basic'
import BarChartGrouped from '../../charts/src/components/bar-chart/examples/grouped'
import BarChartStacked from '../../charts/src/components/bar-chart/examples/stacked'
import BreadcrumbBasic from '../../ui/src/components/breadcrumb/examples/basic'
import BreadcrumbCollapsed from '../../ui/src/components/breadcrumb/examples/collapsed'
import ButtonBasic from '../../ui/src/components/button/examples/basic'
import ButtonVariants from '../../ui/src/components/button/examples/variants'
import ButtonSizes from '../../ui/src/components/button/examples/sizes'
import ButtonWithIcon from '../../ui/src/components/button/examples/with-icon'
import ButtonLoading from '../../ui/src/components/button/examples/loading'
import ButtonDisabled from '../../ui/src/components/button/examples/disabled'
import ButtonFullWidth from '../../ui/src/components/button/examples/full-width'
import ButtonGroupBasic from '../../ui/src/components/button-group/examples/basic'
import ButtonGroupSplit from '../../ui/src/components/button-group/examples/split'
import ButtonGroupOrientation from '../../ui/src/components/button-group/examples/orientation'
import CalendarBasic from '../../ui/src/components/calendar/examples/basic'
import CalendarRange from '../../ui/src/components/calendar/examples/range'
import CardBasic from '../../ui/src/components/card/examples/basic'
import CardVariants from '../../ui/src/components/card/examples/variants'
import CardInteractive from '../../ui/src/components/card/examples/interactive'
import CheckboxBasic from '../../ui/src/components/checkbox/examples/basic'
import CheckboxIndeterminate from '../../ui/src/components/checkbox/examples/indeterminate'
import ChipFilter from '../../ui/src/components/chip/examples/filter'
import ChipInput from '../../ui/src/components/chip/examples/input'
import CircularProgressBasic from '../../ui/src/components/circular-progress/examples/basic'
import CircularProgressSizes from '../../ui/src/components/circular-progress/examples/sizes'
import CollapsibleBasic from '../../ui/src/components/collapsible/examples/basic'
import CollapsibleSettings from '../../ui/src/components/collapsible/examples/settings'
import ComboboxBasic from '../../ui/src/components/combobox/examples/basic'
import CommandPaletteBasic from '../../ui/src/components/command-palette/examples/basic'
import ContainerContainer from '../../ui/src/components/layout/examples/container'
import ContainerGutter from '../../ui/src/components/layout/examples/gutter'
import ContextMenuBasic from '../../ui/src/components/context-menu/examples/basic'
import ContextMenuList from '../../ui/src/components/context-menu/examples/list'
import DataGridBasic from '../../data/src/components/data-grid/examples/basic'
import DataGridReadOnly from '../../data/src/components/data-grid/examples/read-only'
import DataTableBasic from '../../data/src/components/data-table/examples/basic'
import DataTableStates from '../../data/src/components/data-table/examples/states'
import DatePickerBasic from '../../ui/src/components/date-picker/examples/basic'
import DateRangePickerBasic from '../../ui/src/components/date-range-picker/examples/basic'
import DialogBasic from '../../ui/src/components/dialog/examples/basic'
import DialogConfirm from '../../ui/src/components/dialog/examples/confirm'
import DrawerBasic from '../../ui/src/components/drawer/examples/basic'
import DrawerFilters from '../../ui/src/components/drawer/examples/filters'
import DropdownMenuBasic from '../../ui/src/components/dropdown-menu/examples/basic'
import DropdownMenuOptions from '../../ui/src/components/dropdown-menu/examples/options'
import EmptyStateBasic from '../../ui/src/components/empty-state/examples/basic'
import EmptyStateSearch from '../../ui/src/components/empty-state/examples/search'
import ErrorStateBasic from '../../ui/src/components/error-state/examples/basic'
import FieldBasic from '../../ui/src/components/field/examples/basic'
import FieldDescription from '../../ui/src/components/field/examples/description'
import FieldRequiredOptional from '../../ui/src/components/field/examples/required-optional'
import FieldValidation from '../../ui/src/components/field/examples/validation'
import FieldDisabled from '../../ui/src/components/field/examples/disabled'
import FieldHorizontal from '../../ui/src/components/field/examples/horizontal'
import FieldCompound from '../../ui/src/components/field/examples/compound'
import FieldRichContent from '../../ui/src/components/field/examples/rich-content'
import FieldForm from '../../ui/src/components/field/examples/form'
import FileDropzoneBasic from '../../ui/src/components/file-dropzone/examples/basic'
import FileUploadBasic from '../../ui/src/components/file-upload/examples/basic'
import FileUploadMultiple from '../../ui/src/components/file-upload/examples/multiple'
import FabBasic from '../../ui/src/components/fab/examples/basic'
import FabExtended from '../../ui/src/components/fab/examples/extended'
import FormBasic from '../../ui/src/components/form/examples/basic'
import FormTitleDescription from '../../ui/src/components/form/examples/title-description'
import FormFooter from '../../ui/src/components/form/examples/footer'
import FormLoading from '../../ui/src/components/form/examples/loading'
import FormHorizontal from '../../ui/src/components/form/examples/horizontal'
import FormDisabled from '../../ui/src/components/form/examples/disabled'
import FormValidation from '../../ui/src/components/form/examples/validation'
import FormCustomStyling from '../../ui/src/components/form/examples/custom-styling'
import GridTwoColumn84 from '../../ui/src/components/layout/examples/two-column-8-4'
import GridSidebar39 from '../../ui/src/components/layout/examples/sidebar-3-9'
import GridResponsiveCards from '../../ui/src/components/layout/examples/responsive-cards'
import GridOffset from '../../ui/src/components/layout/examples/offset'
import GridGrid from '../../ui/src/components/layout/examples/grid'
import HoverCardBasic from '../../ui/src/components/hover-card/examples/basic'
import IconButtonBasic from '../../ui/src/components/icon-button/examples/basic'
import IconButtonVariants from '../../ui/src/components/icon-button/examples/variants'
import IconButtonSizes from '../../ui/src/components/icon-button/examples/sizes'
import ImageBasic from '../../ui/src/components/image/examples/basic'
import ImageFit from '../../ui/src/components/image/examples/fit'
import ImageFallback from '../../ui/src/components/image/examples/fallback'
import ImageGalleryBasic from '../../ui/src/components/image-gallery/examples/basic'
import InputBasic from '../../ui/src/components/input/examples/basic'
import InputSizes from '../../ui/src/components/input/examples/sizes'
import InputStates from '../../ui/src/components/input/examples/states'
import KpiCardBasic from '../../data/src/components/kpi-card/examples/basic'
import KpiCardGrid from '../../data/src/components/kpi-card/examples/grid'
import KpiCardWithProgress from '../../data/src/components/kpi-card/examples/with-progress'
import KpiCardLoading from '../../data/src/components/kpi-card/examples/loading'
import LabelBasic from '../../ui/src/components/label/examples/basic'
import LineChartBasic from '../../charts/src/components/line-chart/examples/basic'
import LineChartMultiple from '../../charts/src/components/line-chart/examples/multiple'
import ListBasic from '../../ui/src/components/list/examples/basic'
import ListInteractive from '../../ui/src/components/list/examples/interactive'
import ListWithAvatars from '../../ui/src/components/list/examples/with-avatars'
import LoadingButtonBasic from '../../ui/src/components/loading-button/examples/basic'
import LoadingButtonLoadingText from '../../ui/src/components/loading-button/examples/loading-text'
import LoadingButtonCustomSpinner from '../../ui/src/components/loading-button/examples/custom-spinner'
import LoadingButtonSpinnerPosition from '../../ui/src/components/loading-button/examples/spinner-position'
import LoadingButtonAsync from '../../ui/src/components/loading-button/examples/async'
import MenuBasic from '../../ui/src/components/menu/examples/basic'
import MenuActions from '../../ui/src/components/menu/examples/actions'
import MultiSelectBasic from '../../ui/src/components/multi-select/examples/basic'
import NavigationBarBasic from '../../ui/src/components/navigation-bar/examples/basic'
import NavigationMenuBasic from '../../ui/src/components/navigation-menu/examples/basic'
import NumberInputBasic from '../../ui/src/components/number-input/examples/basic'
import NumberInputDecimal from '../../ui/src/components/number-input/examples/decimal'
import OtpInputBasic from '../../ui/src/components/otp-input/examples/basic'
import OtpInputGrouped from '../../ui/src/components/otp-input/examples/grouped'
import PaginationBasic from '../../ui/src/components/pagination/examples/basic'
import PaginationControlled from '../../ui/src/components/pagination/examples/controlled'
import PaginationCompact from '../../ui/src/components/pagination/examples/compact'
import PasswordInputBasic from '../../ui/src/components/password-input/examples/basic'
import PieChartBasic from '../../charts/src/components/pie-chart/examples/basic'
import PieChartOther from '../../charts/src/components/pie-chart/examples/other'
import PopoverBasic from '../../ui/src/components/popover/examples/basic'
import PopoverFilter from '../../ui/src/components/popover/examples/filter'
import ProgressBasic from '../../ui/src/components/progress/examples/basic'
import RadioGroupBasic from '../../ui/src/components/radio-group/examples/basic'
import ResizablePanelBasic from '../../ui/src/components/resizable-panel/examples/basic'
import ResizablePanelVertical from '../../ui/src/components/resizable-panel/examples/vertical'
import ResizablePanelCollapsible from '../../ui/src/components/resizable-panel/examples/collapsible'
import RichTextEditorBasic from '../../editor/src/components/rich-text-editor/examples/basic'
import RichTextEditorMinimal from '../../editor/src/components/rich-text-editor/examples/minimal'
import RichTextEditorContent from '../../editor/src/components/rich-text-editor/examples/content'
import ScrollAreaBasic from '../../ui/src/components/scroll-area/examples/basic'
import ScrollAreaHorizontal from '../../ui/src/components/scroll-area/examples/horizontal'
import SearchBasic from '../../ui/src/components/search/examples/basic'
import SearchLive from '../../ui/src/components/search/examples/live'
import SectionHero from '../../ui/src/components/section/examples/hero'
import SectionFeatures from '../../ui/src/components/section/examples/features'
import SectionCallToAction from '../../ui/src/components/section/examples/call-to-action'
import SelectBasic from '../../ui/src/components/select/examples/basic'
import SelectGroups from '../../ui/src/components/select/examples/groups'
import SeparatorBasic from '../../ui/src/components/separator/examples/basic'
import SeparatorLogin from '../../ui/src/components/separator/examples/login'
import SheetBasic from '../../ui/src/components/sheet/examples/basic'
import SheetScroll from '../../ui/src/components/sheet/examples/scroll'
import ShowHideNavigation from '../../ui/src/components/show-hide/examples/navigation'
import ShowHideBreakpointValue from '../../ui/src/components/show-hide/examples/breakpoint-value'
import SidebarBasic from '../../ui/src/components/sidebar/examples/basic'
import SidebarDrawer from '../../ui/src/components/sidebar/examples/drawer'
import SkeletonCard from '../../ui/src/components/skeleton/examples/card'
import SliderBasic from '../../ui/src/components/slider/examples/basic'
import SliderRange from '../../ui/src/components/slider/examples/range'
import SnackbarBasic from '../../ui/src/components/snackbar/examples/basic'
import SnackbarPersistent from '../../ui/src/components/snackbar/examples/persistent'
import SpinnerBasic from '../../ui/src/components/spinner/examples/basic'
import StackBasic from '../../ui/src/components/layout/examples/basic'
import StackResponsiveDirection from '../../ui/src/components/layout/examples/responsive-direction'
import StackToolbar from '../../ui/src/components/layout/examples/toolbar'
import StackWrap from '../../ui/src/components/layout/examples/wrap'
import StackResponsive from '../../ui/src/components/layout/examples/responsive'
import StatBasic from '../../data/src/components/stat/examples/basic'
import StatTrends from '../../data/src/components/stat/examples/trends'
import StatSizes from '../../data/src/components/stat/examples/sizes'
import StepperBasic from '../../ui/src/components/stepper/examples/basic'
import StepperVertical from '../../ui/src/components/stepper/examples/vertical'
import StickyPageHeader from '../../ui/src/components/sticky/examples/page-header'
import StickyListHeaders from '../../ui/src/components/sticky/examples/list-headers'
import SwitchSettings from '../../ui/src/components/switch/examples/settings'
import TableBasic from '../../data/src/components/table/examples/basic'
import TableSortable from '../../data/src/components/table/examples/sortable'
import TableScroll from '../../data/src/components/table/examples/scroll'
import TabsBasic from '../../ui/src/components/tabs/examples/basic'
import TabsUnderline from '../../ui/src/components/tabs/examples/underline'
import TextareaBasic from '../../ui/src/components/textarea/examples/basic'
import TimePickerBasic from '../../ui/src/components/time-picker/examples/basic'
import TimePickerTwelveHour from '../../ui/src/components/time-picker/examples/twelve-hour'
import TimelineBasic from '../../data/src/components/timeline/examples/basic'
import TimelineTones from '../../data/src/components/timeline/examples/tones'
import TimelineActivity from '../../data/src/components/timeline/examples/activity'
import ToastTypes from '../../ui/src/components/toast/examples/types'
import ToastAction from '../../ui/src/components/toast/examples/action'
import ToggleBasic from '../../ui/src/components/toggle/examples/basic'
import ToggleControlled from '../../ui/src/components/toggle/examples/controlled'
import ToggleGroupBasic from '../../ui/src/components/toggle-group/examples/basic'
import ToggleGroupMultiple from '../../ui/src/components/toggle-group/examples/multiple'
import TooltipBasic from '../../ui/src/components/tooltip/examples/basic'
import TreeViewBasic from '../../data/src/components/tree-view/examples/basic'
import TreeViewControlled from '../../data/src/components/tree-view/examples/controlled'
import TypographyScale from '../../ui/src/components/typography/examples/scale'
import TypographyTones from '../../ui/src/components/typography/examples/tones'
import VideoBasic from '../../ui/src/components/video/examples/basic'
import VideoMutedLoop from '../../ui/src/components/video/examples/muted-loop'
import WrapTags from '../../ui/src/components/layout/examples/tags'

export const examples: Record<string, Record<string, ComponentType>> = {
  'accordion': {
    'basic': AccordionBasic,
    'card': AccordionCard,
  },
  'alert': {
    'variants': AlertVariants,
  },
  'alert-dialog': {
    'basic': AlertDialogBasic,
    'async': AlertDialogAsync,
  },
  'area-chart': {
    'basic': AreaChartBasic,
    'stacked': AreaChartStacked,
  },
  'aspect-ratio': {
    'basic': AspectRatioBasic,
    'ratios': AspectRatioRatios,
  },
  'audio-player': {
    'basic': AudioPlayerBasic,
    'compact': AudioPlayerCompact,
  },
  'autocomplete': {
    'basic': AutocompleteBasic,
  },
  'avatar': {
    'basic': AvatarBasic,
    'sizes': AvatarSizes,
    'group': AvatarGroup,
  },
  'badge': {
    'variants': BadgeVariants,
    'with-icon': BadgeWithIcon,
  },
  'bar-chart': {
    'basic': BarChartBasic,
    'grouped': BarChartGrouped,
    'stacked': BarChartStacked,
  },
  'breadcrumb': {
    'basic': BreadcrumbBasic,
    'collapsed': BreadcrumbCollapsed,
  },
  'button': {
    'basic': ButtonBasic,
    'variants': ButtonVariants,
    'sizes': ButtonSizes,
    'with-icon': ButtonWithIcon,
    'loading': ButtonLoading,
    'disabled': ButtonDisabled,
    'full-width': ButtonFullWidth,
  },
  'button-group': {
    'basic': ButtonGroupBasic,
    'split': ButtonGroupSplit,
    'orientation': ButtonGroupOrientation,
  },
  'calendar': {
    'basic': CalendarBasic,
    'range': CalendarRange,
  },
  'card': {
    'basic': CardBasic,
    'variants': CardVariants,
    'interactive': CardInteractive,
  },
  'checkbox': {
    'basic': CheckboxBasic,
    'indeterminate': CheckboxIndeterminate,
  },
  'chip': {
    'filter': ChipFilter,
    'input': ChipInput,
  },
  'circular-progress': {
    'basic': CircularProgressBasic,
    'sizes': CircularProgressSizes,
  },
  'collapsible': {
    'basic': CollapsibleBasic,
    'settings': CollapsibleSettings,
  },
  'combobox': {
    'basic': ComboboxBasic,
  },
  'command-palette': {
    'basic': CommandPaletteBasic,
  },
  'container': {
    'container': ContainerContainer,
    'gutter': ContainerGutter,
  },
  'context-menu': {
    'basic': ContextMenuBasic,
    'list': ContextMenuList,
  },
  'data-grid': {
    'basic': DataGridBasic,
    'read-only': DataGridReadOnly,
  },
  'data-table': {
    'basic': DataTableBasic,
    'states': DataTableStates,
  },
  'date-picker': {
    'basic': DatePickerBasic,
  },
  'date-range-picker': {
    'basic': DateRangePickerBasic,
  },
  'dialog': {
    'basic': DialogBasic,
    'confirm': DialogConfirm,
  },
  'drawer': {
    'basic': DrawerBasic,
    'filters': DrawerFilters,
  },
  'dropdown-menu': {
    'basic': DropdownMenuBasic,
    'options': DropdownMenuOptions,
  },
  'empty-state': {
    'basic': EmptyStateBasic,
    'search': EmptyStateSearch,
  },
  'error-state': {
    'basic': ErrorStateBasic,
  },
  'field': {
    'basic': FieldBasic,
    'description': FieldDescription,
    'required-optional': FieldRequiredOptional,
    'validation': FieldValidation,
    'disabled': FieldDisabled,
    'horizontal': FieldHorizontal,
    'compound': FieldCompound,
    'rich-content': FieldRichContent,
    'form': FieldForm,
  },
  'file-dropzone': {
    'basic': FileDropzoneBasic,
  },
  'file-upload': {
    'basic': FileUploadBasic,
    'multiple': FileUploadMultiple,
  },
  'fab': {
    'basic': FabBasic,
    'extended': FabExtended,
  },
  'form': {
    'basic': FormBasic,
    'title-description': FormTitleDescription,
    'footer': FormFooter,
    'loading': FormLoading,
    'horizontal': FormHorizontal,
    'disabled': FormDisabled,
    'validation': FormValidation,
    'custom-styling': FormCustomStyling,
  },
  'grid': {
    'two-column-8-4': GridTwoColumn84,
    'sidebar-3-9': GridSidebar39,
    'responsive-cards': GridResponsiveCards,
    'offset': GridOffset,
    'grid': GridGrid,
  },
  'hover-card': {
    'basic': HoverCardBasic,
  },
  'icon-button': {
    'basic': IconButtonBasic,
    'variants': IconButtonVariants,
    'sizes': IconButtonSizes,
  },
  'image': {
    'basic': ImageBasic,
    'fit': ImageFit,
    'fallback': ImageFallback,
  },
  'image-gallery': {
    'basic': ImageGalleryBasic,
  },
  'input': {
    'basic': InputBasic,
    'sizes': InputSizes,
    'states': InputStates,
  },
  'kpi-card': {
    'basic': KpiCardBasic,
    'grid': KpiCardGrid,
    'with-progress': KpiCardWithProgress,
    'loading': KpiCardLoading,
  },
  'label': {
    'basic': LabelBasic,
  },
  'line-chart': {
    'basic': LineChartBasic,
    'multiple': LineChartMultiple,
  },
  'list': {
    'basic': ListBasic,
    'interactive': ListInteractive,
    'with-avatars': ListWithAvatars,
  },
  'loading-button': {
    'basic': LoadingButtonBasic,
    'loading-text': LoadingButtonLoadingText,
    'custom-spinner': LoadingButtonCustomSpinner,
    'spinner-position': LoadingButtonSpinnerPosition,
    'async': LoadingButtonAsync,
  },
  'menu': {
    'basic': MenuBasic,
    'actions': MenuActions,
  },
  'multi-select': {
    'basic': MultiSelectBasic,
  },
  'navigation-bar': {
    'basic': NavigationBarBasic,
  },
  'navigation-menu': {
    'basic': NavigationMenuBasic,
  },
  'number-input': {
    'basic': NumberInputBasic,
    'decimal': NumberInputDecimal,
  },
  'otp-input': {
    'basic': OtpInputBasic,
    'grouped': OtpInputGrouped,
  },
  'pagination': {
    'basic': PaginationBasic,
    'controlled': PaginationControlled,
    'compact': PaginationCompact,
  },
  'password-input': {
    'basic': PasswordInputBasic,
  },
  'pie-chart': {
    'basic': PieChartBasic,
    'other': PieChartOther,
  },
  'popover': {
    'basic': PopoverBasic,
    'filter': PopoverFilter,
  },
  'progress': {
    'basic': ProgressBasic,
  },
  'radio-group': {
    'basic': RadioGroupBasic,
  },
  'resizable-panel': {
    'basic': ResizablePanelBasic,
    'vertical': ResizablePanelVertical,
    'collapsible': ResizablePanelCollapsible,
  },
  'rich-text-editor': {
    'basic': RichTextEditorBasic,
    'minimal': RichTextEditorMinimal,
    'content': RichTextEditorContent,
  },
  'scroll-area': {
    'basic': ScrollAreaBasic,
    'horizontal': ScrollAreaHorizontal,
  },
  'search': {
    'basic': SearchBasic,
    'live': SearchLive,
  },
  'section': {
    'hero': SectionHero,
    'features': SectionFeatures,
    'call-to-action': SectionCallToAction,
  },
  'select': {
    'basic': SelectBasic,
    'groups': SelectGroups,
  },
  'separator': {
    'basic': SeparatorBasic,
    'login': SeparatorLogin,
  },
  'sheet': {
    'basic': SheetBasic,
    'scroll': SheetScroll,
  },
  'show-hide': {
    'navigation': ShowHideNavigation,
    'breakpoint-value': ShowHideBreakpointValue,
  },
  'sidebar': {
    'basic': SidebarBasic,
    'drawer': SidebarDrawer,
  },
  'skeleton': {
    'card': SkeletonCard,
  },
  'slider': {
    'basic': SliderBasic,
    'range': SliderRange,
  },
  'snackbar': {
    'basic': SnackbarBasic,
    'persistent': SnackbarPersistent,
  },
  'spinner': {
    'basic': SpinnerBasic,
  },
  'stack': {
    'basic': StackBasic,
    'responsive-direction': StackResponsiveDirection,
    'toolbar': StackToolbar,
    'wrap': StackWrap,
    'responsive': StackResponsive,
  },
  'stat': {
    'basic': StatBasic,
    'trends': StatTrends,
    'sizes': StatSizes,
  },
  'stepper': {
    'basic': StepperBasic,
    'vertical': StepperVertical,
  },
  'sticky': {
    'page-header': StickyPageHeader,
    'list-headers': StickyListHeaders,
  },
  'switch': {
    'settings': SwitchSettings,
  },
  'table': {
    'basic': TableBasic,
    'sortable': TableSortable,
    'scroll': TableScroll,
  },
  'tabs': {
    'basic': TabsBasic,
    'underline': TabsUnderline,
  },
  'textarea': {
    'basic': TextareaBasic,
  },
  'time-picker': {
    'basic': TimePickerBasic,
    'twelve-hour': TimePickerTwelveHour,
  },
  'timeline': {
    'basic': TimelineBasic,
    'tones': TimelineTones,
    'activity': TimelineActivity,
  },
  'toast': {
    'types': ToastTypes,
    'action': ToastAction,
  },
  'toggle': {
    'basic': ToggleBasic,
    'controlled': ToggleControlled,
  },
  'toggle-group': {
    'basic': ToggleGroupBasic,
    'multiple': ToggleGroupMultiple,
  },
  'tooltip': {
    'basic': TooltipBasic,
  },
  'tree-view': {
    'basic': TreeViewBasic,
    'controlled': TreeViewControlled,
  },
  'typography': {
    'scale': TypographyScale,
    'tones': TypographyTones,
  },
  'video': {
    'basic': VideoBasic,
    'muted-loop': VideoMutedLoop,
  },
  'wrap': {
    'tags': WrapTags,
  },
}
