// AUTO-GENERATED by scripts/generate-catalog.mjs — do not edit by hand.
import accordionMeta from '../../ui/src/components/accordion/accordion.meta'
import alertMeta from '../../ui/src/components/alert/alert.meta'
import alertDialogMeta from '../../ui/src/components/alert-dialog/alert-dialog.meta'
import areaChartMeta from '../../ui/src/components/area-chart/area-chart.meta'
import aspectRatioMeta from '../../ui/src/components/aspect-ratio/aspect-ratio.meta'
import audioPlayerMeta from '../../ui/src/components/audio-player/audio-player.meta'
import autocompleteMeta from '../../ui/src/components/autocomplete/autocomplete.meta'
import avatarMeta from '../../ui/src/components/avatar/avatar.meta'
import badgeMeta from '../../ui/src/components/badge/badge.meta'
import barChartMeta from '../../ui/src/components/bar-chart/bar-chart.meta'
import breadcrumbMeta from '../../ui/src/components/breadcrumb/breadcrumb.meta'
import buttonMeta from '../../ui/src/components/button/button.meta'
import buttonGroupMeta from '../../ui/src/components/button-group/button-group.meta'
import calendarMeta from '../../ui/src/components/calendar/calendar.meta'
import cardMeta from '../../ui/src/components/card/card.meta'
import checkboxMeta from '../../ui/src/components/checkbox/checkbox.meta'
import chipMeta from '../../ui/src/components/chip/chip.meta'
import circularProgressMeta from '../../ui/src/components/circular-progress/circular-progress.meta'
import collapsibleMeta from '../../ui/src/components/collapsible/collapsible.meta'
import comboboxMeta from '../../ui/src/components/combobox/combobox.meta'
import commandPaletteMeta from '../../ui/src/components/command-palette/command-palette.meta'
import containerMeta from '../../ui/src/components/layout/container.meta'
import contextMenuMeta from '../../ui/src/components/context-menu/context-menu.meta'
import dataGridMeta from '../../ui/src/components/data-grid/data-grid.meta'
import dataTableMeta from '../../ui/src/components/data-table/data-table.meta'
import datePickerMeta from '../../ui/src/components/date-picker/date-picker.meta'
import dateRangePickerMeta from '../../ui/src/components/date-range-picker/date-range-picker.meta'
import dialogMeta from '../../ui/src/components/dialog/dialog.meta'
import drawerMeta from '../../ui/src/components/drawer/drawer.meta'
import dropdownMenuMeta from '../../ui/src/components/dropdown-menu/dropdown-menu.meta'
import emptyStateMeta from '../../ui/src/components/empty-state/empty-state.meta'
import errorStateMeta from '../../ui/src/components/error-state/error-state.meta'
import fileDropzoneMeta from '../../ui/src/components/file-dropzone/file-dropzone.meta'
import fileUploadMeta from '../../ui/src/components/file-upload/file-upload.meta'
import fabMeta from '../../ui/src/components/fab/fab.meta'
import formMeta from '../../ui/src/components/form/form.meta'
import formFieldMeta from '../../ui/src/components/form-field/form-field.meta'
import gridMeta from '../../ui/src/components/layout/grid.meta'
import hoverCardMeta from '../../ui/src/components/hover-card/hover-card.meta'
import iconButtonMeta from '../../ui/src/components/icon-button/icon-button.meta'
import imageMeta from '../../ui/src/components/image/image.meta'
import imageGalleryMeta from '../../ui/src/components/image-gallery/image-gallery.meta'
import inputMeta from '../../ui/src/components/input/input.meta'
import kpiCardMeta from '../../ui/src/components/kpi-card/kpi-card.meta'
import labelMeta from '../../ui/src/components/label/label.meta'
import lineChartMeta from '../../ui/src/components/line-chart/line-chart.meta'
import listMeta from '../../ui/src/components/list/list.meta'
import loadingButtonMeta from '../../ui/src/components/loading-button/loading-button.meta'
import menuMeta from '../../ui/src/components/menu/menu.meta'
import multiSelectMeta from '../../ui/src/components/multi-select/multi-select.meta'
import navigationBarMeta from '../../ui/src/components/navigation-bar/navigation-bar.meta'
import navigationMenuMeta from '../../ui/src/components/navigation-menu/navigation-menu.meta'
import numberInputMeta from '../../ui/src/components/number-input/number-input.meta'
import otpInputMeta from '../../ui/src/components/otp-input/otp-input.meta'
import paginationMeta from '../../ui/src/components/pagination/pagination.meta'
import passwordInputMeta from '../../ui/src/components/password-input/password-input.meta'
import pieChartMeta from '../../ui/src/components/pie-chart/pie-chart.meta'
import popoverMeta from '../../ui/src/components/popover/popover.meta'
import progressMeta from '../../ui/src/components/progress/progress.meta'
import radioGroupMeta from '../../ui/src/components/radio-group/radio-group.meta'
import resizablePanelMeta from '../../ui/src/components/resizable-panel/resizable-panel.meta'
import richTextEditorMeta from '../../ui/src/components/rich-text-editor/rich-text-editor.meta'
import scrollAreaMeta from '../../ui/src/components/scroll-area/scroll-area.meta'
import searchMeta from '../../ui/src/components/search/search.meta'
import selectMeta from '../../ui/src/components/select/select.meta'
import separatorMeta from '../../ui/src/components/separator/separator.meta'
import sheetMeta from '../../ui/src/components/sheet/sheet.meta'
import sidebarMeta from '../../ui/src/components/sidebar/sidebar.meta'
import skeletonMeta from '../../ui/src/components/skeleton/skeleton.meta'
import sliderMeta from '../../ui/src/components/slider/slider.meta'
import snackbarMeta from '../../ui/src/components/snackbar/snackbar.meta'
import spinnerMeta from '../../ui/src/components/spinner/spinner.meta'
import stackMeta from '../../ui/src/components/layout/stack.meta'
import statMeta from '../../ui/src/components/stat/stat.meta'
import stepperMeta from '../../ui/src/components/stepper/stepper.meta'
import switchMeta from '../../ui/src/components/switch/switch.meta'
import tableMeta from '../../ui/src/components/table/table.meta'
import tabsMeta from '../../ui/src/components/tabs/tabs.meta'
import textareaMeta from '../../ui/src/components/textarea/textarea.meta'
import timePickerMeta from '../../ui/src/components/time-picker/time-picker.meta'
import timelineMeta from '../../ui/src/components/timeline/timeline.meta'
import toastMeta from '../../ui/src/components/toast/toast.meta'
import toggleMeta from '../../ui/src/components/toggle/toggle.meta'
import toggleGroupMeta from '../../ui/src/components/toggle-group/toggle-group.meta'
import tooltipMeta from '../../ui/src/components/tooltip/tooltip.meta'
import treeViewMeta from '../../ui/src/components/tree-view/tree-view.meta'
import typographyMeta from '../../ui/src/components/typography/typography.meta'
import videoMeta from '../../ui/src/components/video/video.meta'
import type { CatalogComponent, ComponentPackage } from './types'

/** Published component packages, in dependency order. */
export const packages: ComponentPackage[] = [
  { name: '@advui/core', title: 'Core', description: 'Cross-platform React / React Native component library built on Tamagui.' },
]

export const components: CatalogComponent[] = [
  { ...accordionMeta, package: '@advui/core' },
  { ...alertMeta, package: '@advui/core' },
  { ...alertDialogMeta, package: '@advui/core' },
  { ...areaChartMeta, package: '@advui/core' },
  { ...aspectRatioMeta, package: '@advui/core' },
  { ...audioPlayerMeta, package: '@advui/core' },
  { ...autocompleteMeta, package: '@advui/core' },
  { ...avatarMeta, package: '@advui/core' },
  { ...badgeMeta, package: '@advui/core' },
  { ...barChartMeta, package: '@advui/core' },
  { ...breadcrumbMeta, package: '@advui/core' },
  { ...buttonMeta, package: '@advui/core' },
  { ...buttonGroupMeta, package: '@advui/core' },
  { ...calendarMeta, package: '@advui/core' },
  { ...cardMeta, package: '@advui/core' },
  { ...checkboxMeta, package: '@advui/core' },
  { ...chipMeta, package: '@advui/core' },
  { ...circularProgressMeta, package: '@advui/core' },
  { ...collapsibleMeta, package: '@advui/core' },
  { ...comboboxMeta, package: '@advui/core' },
  { ...commandPaletteMeta, package: '@advui/core' },
  { ...containerMeta, package: '@advui/core' },
  { ...contextMenuMeta, package: '@advui/core' },
  { ...dataGridMeta, package: '@advui/core' },
  { ...dataTableMeta, package: '@advui/core' },
  { ...datePickerMeta, package: '@advui/core' },
  { ...dateRangePickerMeta, package: '@advui/core' },
  { ...dialogMeta, package: '@advui/core' },
  { ...drawerMeta, package: '@advui/core' },
  { ...dropdownMenuMeta, package: '@advui/core' },
  { ...emptyStateMeta, package: '@advui/core' },
  { ...errorStateMeta, package: '@advui/core' },
  { ...fileDropzoneMeta, package: '@advui/core' },
  { ...fileUploadMeta, package: '@advui/core' },
  { ...fabMeta, package: '@advui/core' },
  { ...formMeta, package: '@advui/core' },
  { ...formFieldMeta, package: '@advui/core' },
  { ...gridMeta, package: '@advui/core' },
  { ...hoverCardMeta, package: '@advui/core' },
  { ...iconButtonMeta, package: '@advui/core' },
  { ...imageMeta, package: '@advui/core' },
  { ...imageGalleryMeta, package: '@advui/core' },
  { ...inputMeta, package: '@advui/core' },
  { ...kpiCardMeta, package: '@advui/core' },
  { ...labelMeta, package: '@advui/core' },
  { ...lineChartMeta, package: '@advui/core' },
  { ...listMeta, package: '@advui/core' },
  { ...loadingButtonMeta, package: '@advui/core' },
  { ...menuMeta, package: '@advui/core' },
  { ...multiSelectMeta, package: '@advui/core' },
  { ...navigationBarMeta, package: '@advui/core' },
  { ...navigationMenuMeta, package: '@advui/core' },
  { ...numberInputMeta, package: '@advui/core' },
  { ...otpInputMeta, package: '@advui/core' },
  { ...paginationMeta, package: '@advui/core' },
  { ...passwordInputMeta, package: '@advui/core' },
  { ...pieChartMeta, package: '@advui/core' },
  { ...popoverMeta, package: '@advui/core' },
  { ...progressMeta, package: '@advui/core' },
  { ...radioGroupMeta, package: '@advui/core' },
  { ...resizablePanelMeta, package: '@advui/core' },
  { ...richTextEditorMeta, package: '@advui/core' },
  { ...scrollAreaMeta, package: '@advui/core' },
  { ...searchMeta, package: '@advui/core' },
  { ...selectMeta, package: '@advui/core' },
  { ...separatorMeta, package: '@advui/core' },
  { ...sheetMeta, package: '@advui/core' },
  { ...sidebarMeta, package: '@advui/core' },
  { ...skeletonMeta, package: '@advui/core' },
  { ...sliderMeta, package: '@advui/core' },
  { ...snackbarMeta, package: '@advui/core' },
  { ...spinnerMeta, package: '@advui/core' },
  { ...stackMeta, package: '@advui/core' },
  { ...statMeta, package: '@advui/core' },
  { ...stepperMeta, package: '@advui/core' },
  { ...switchMeta, package: '@advui/core' },
  { ...tableMeta, package: '@advui/core' },
  { ...tabsMeta, package: '@advui/core' },
  { ...textareaMeta, package: '@advui/core' },
  { ...timePickerMeta, package: '@advui/core' },
  { ...timelineMeta, package: '@advui/core' },
  { ...toastMeta, package: '@advui/core' },
  { ...toggleMeta, package: '@advui/core' },
  { ...toggleGroupMeta, package: '@advui/core' },
  { ...tooltipMeta, package: '@advui/core' },
  { ...treeViewMeta, package: '@advui/core' },
  { ...typographyMeta, package: '@advui/core' },
  { ...videoMeta, package: '@advui/core' },
]

export function getComponent(slug: string): CatalogComponent | undefined {
  return components.find((component) => component.slug === slug)
}

export { roadmap, type RoadmapItem } from './roadmap'
export type { CatalogComponent, ComponentPackage } from './types'
export { categories, defineMeta } from '@advui/core/meta'
export type * from '@advui/core/meta'
