// AUTO-GENERATED by scripts/generate-catalog.mjs — do not edit by hand.
import type { ComponentMeta } from '@advui/core/meta'
import richTextEditorMeta from '../components/rich-text-editor/rich-text-editor.meta'

/** The metadata of every @advui/editor component, sorted by slug. */
export const components: ComponentMeta[] = [
  richTextEditorMeta,
]
