// AUTO-GENERATED by scripts/generate-icons.mjs. Do not edit.
import { createIcon } from './createIcon'
import { alertCircleNode, alertTriangleNode, alignCenterNode, alignLeftNode, alignRightNode, arrowLeftNode, arrowRightNode, barChartNode, bellNode, boldNode, calendarNode, checkNode, checkCircleNode, chevronDownNode, chevronLeftNode, chevronRightNode, chevronUpNode, chevronsUpDownNode, circleNode, copyNode, creditCardNode, downloadNode, editNode, externalLinkNode, eyeNode, eyeOffNode, fileNode, filterNode, folderNode, codeNode, gitBranchNode, globeNode, heartNode, homeNode, imageNode, infoNode, italicNode, layoutGridNode, listNode, loaderNode, lockNode, logOutNode, mailNode, menuNode, minusNode, monitorNode, moonNode, moreHorizontalNode, packageNode, paletteNode, plusNode, searchNode, settingsNode, shoppingCartNode, smartphoneNode, starNode, sunNode, trashNode, trendingUpNode, underlineNode, uploadNode, userNode, usersNode, xNode, xCircleNode, gripHorizontalNode, gripVerticalNode, headingNode, linkNode, listOrderedNode, pauseNode, playNode, quoteNode, rotateCcwNode, rotateCwNode, strikethroughNode, volumeNode, volumeOffNode } from './generated'
import type { IconComponent } from './types'

export const AlertCircleIcon = /* @__PURE__ */ createIcon('alert-circle', alertCircleNode)
export const AlertTriangleIcon = /* @__PURE__ */ createIcon('alert-triangle', alertTriangleNode)
export const AlignCenterIcon = /* @__PURE__ */ createIcon('align-center', alignCenterNode)
export const AlignLeftIcon = /* @__PURE__ */ createIcon('align-left', alignLeftNode)
export const AlignRightIcon = /* @__PURE__ */ createIcon('align-right', alignRightNode)
export const ArrowLeftIcon = /* @__PURE__ */ createIcon('arrow-left', arrowLeftNode)
export const ArrowRightIcon = /* @__PURE__ */ createIcon('arrow-right', arrowRightNode)
export const BarChartIcon = /* @__PURE__ */ createIcon('bar-chart', barChartNode)
export const BellIcon = /* @__PURE__ */ createIcon('bell', bellNode)
export const BoldIcon = /* @__PURE__ */ createIcon('bold', boldNode)
export const CalendarIcon = /* @__PURE__ */ createIcon('calendar', calendarNode)
export const CheckIcon = /* @__PURE__ */ createIcon('check', checkNode)
export const CheckCircleIcon = /* @__PURE__ */ createIcon('check-circle', checkCircleNode)
export const ChevronDownIcon = /* @__PURE__ */ createIcon('chevron-down', chevronDownNode)
export const ChevronLeftIcon = /* @__PURE__ */ createIcon('chevron-left', chevronLeftNode)
export const ChevronRightIcon = /* @__PURE__ */ createIcon('chevron-right', chevronRightNode)
export const ChevronUpIcon = /* @__PURE__ */ createIcon('chevron-up', chevronUpNode)
export const ChevronsUpDownIcon = /* @__PURE__ */ createIcon('chevrons-up-down', chevronsUpDownNode)
export const CircleIcon = /* @__PURE__ */ createIcon('circle', circleNode)
export const CopyIcon = /* @__PURE__ */ createIcon('copy', copyNode)
export const CreditCardIcon = /* @__PURE__ */ createIcon('credit-card', creditCardNode)
export const DownloadIcon = /* @__PURE__ */ createIcon('download', downloadNode)
export const EditIcon = /* @__PURE__ */ createIcon('edit', editNode)
export const ExternalLinkIcon = /* @__PURE__ */ createIcon('external-link', externalLinkNode)
export const EyeIcon = /* @__PURE__ */ createIcon('eye', eyeNode)
export const EyeOffIcon = /* @__PURE__ */ createIcon('eye-off', eyeOffNode)
export const FileIcon = /* @__PURE__ */ createIcon('file', fileNode)
export const FilterIcon = /* @__PURE__ */ createIcon('filter', filterNode)
export const FolderIcon = /* @__PURE__ */ createIcon('folder', folderNode)
export const CodeIcon = /* @__PURE__ */ createIcon('code', codeNode)
export const GitBranchIcon = /* @__PURE__ */ createIcon('git-branch', gitBranchNode)
export const GlobeIcon = /* @__PURE__ */ createIcon('globe', globeNode)
export const HeartIcon = /* @__PURE__ */ createIcon('heart', heartNode)
export const HomeIcon = /* @__PURE__ */ createIcon('home', homeNode)
export const ImageIcon = /* @__PURE__ */ createIcon('image', imageNode)
export const InfoIcon = /* @__PURE__ */ createIcon('info', infoNode)
export const ItalicIcon = /* @__PURE__ */ createIcon('italic', italicNode)
export const LayoutGridIcon = /* @__PURE__ */ createIcon('layout-grid', layoutGridNode)
export const ListIcon = /* @__PURE__ */ createIcon('list', listNode)
export const LoaderIcon = /* @__PURE__ */ createIcon('loader', loaderNode)
export const LockIcon = /* @__PURE__ */ createIcon('lock', lockNode)
export const LogOutIcon = /* @__PURE__ */ createIcon('log-out', logOutNode)
export const MailIcon = /* @__PURE__ */ createIcon('mail', mailNode)
export const MenuIcon = /* @__PURE__ */ createIcon('menu', menuNode)
export const MinusIcon = /* @__PURE__ */ createIcon('minus', minusNode)
export const MonitorIcon = /* @__PURE__ */ createIcon('monitor', monitorNode)
export const MoonIcon = /* @__PURE__ */ createIcon('moon', moonNode)
export const MoreHorizontalIcon = /* @__PURE__ */ createIcon('more-horizontal', moreHorizontalNode)
export const PackageIcon = /* @__PURE__ */ createIcon('package', packageNode)
export const PaletteIcon = /* @__PURE__ */ createIcon('palette', paletteNode)
export const PlusIcon = /* @__PURE__ */ createIcon('plus', plusNode)
export const SearchIcon = /* @__PURE__ */ createIcon('search', searchNode)
export const SettingsIcon = /* @__PURE__ */ createIcon('settings', settingsNode)
export const ShoppingCartIcon = /* @__PURE__ */ createIcon('shopping-cart', shoppingCartNode)
export const SmartphoneIcon = /* @__PURE__ */ createIcon('smartphone', smartphoneNode)
export const StarIcon = /* @__PURE__ */ createIcon('star', starNode)
export const SunIcon = /* @__PURE__ */ createIcon('sun', sunNode)
export const TrashIcon = /* @__PURE__ */ createIcon('trash', trashNode)
export const TrendingUpIcon = /* @__PURE__ */ createIcon('trending-up', trendingUpNode)
export const UnderlineIcon = /* @__PURE__ */ createIcon('underline', underlineNode)
export const UploadIcon = /* @__PURE__ */ createIcon('upload', uploadNode)
export const UserIcon = /* @__PURE__ */ createIcon('user', userNode)
export const UsersIcon = /* @__PURE__ */ createIcon('users', usersNode)
export const XIcon = /* @__PURE__ */ createIcon('x', xNode)
export const XCircleIcon = /* @__PURE__ */ createIcon('x-circle', xCircleNode)
export const GripHorizontalIcon = /* @__PURE__ */ createIcon('grip-horizontal', gripHorizontalNode)
export const GripVerticalIcon = /* @__PURE__ */ createIcon('grip-vertical', gripVerticalNode)
export const HeadingIcon = /* @__PURE__ */ createIcon('heading', headingNode)
export const LinkIcon = /* @__PURE__ */ createIcon('link', linkNode)
export const ListOrderedIcon = /* @__PURE__ */ createIcon('list-ordered', listOrderedNode)
export const PauseIcon = /* @__PURE__ */ createIcon('pause', pauseNode)
export const PlayIcon = /* @__PURE__ */ createIcon('play', playNode)
export const QuoteIcon = /* @__PURE__ */ createIcon('quote', quoteNode)
export const RotateCcwIcon = /* @__PURE__ */ createIcon('rotate-ccw', rotateCcwNode)
export const RotateCwIcon = /* @__PURE__ */ createIcon('rotate-cw', rotateCwNode)
export const StrikethroughIcon = /* @__PURE__ */ createIcon('strikethrough', strikethroughNode)
export const VolumeIcon = /* @__PURE__ */ createIcon('volume', volumeNode)
export const VolumeOffIcon = /* @__PURE__ */ createIcon('volume-off', volumeOffNode)

/** Every built-in icon keyed by name — used by `<Icon name="…" />`. */
export const defaultIcons = {
  'alert-circle': AlertCircleIcon,
  'alert-triangle': AlertTriangleIcon,
  'align-center': AlignCenterIcon,
  'align-left': AlignLeftIcon,
  'align-right': AlignRightIcon,
  'arrow-left': ArrowLeftIcon,
  'arrow-right': ArrowRightIcon,
  'bar-chart': BarChartIcon,
  'bell': BellIcon,
  'bold': BoldIcon,
  'calendar': CalendarIcon,
  'check': CheckIcon,
  'check-circle': CheckCircleIcon,
  'chevron-down': ChevronDownIcon,
  'chevron-left': ChevronLeftIcon,
  'chevron-right': ChevronRightIcon,
  'chevron-up': ChevronUpIcon,
  'chevrons-up-down': ChevronsUpDownIcon,
  'circle': CircleIcon,
  'copy': CopyIcon,
  'credit-card': CreditCardIcon,
  'download': DownloadIcon,
  'edit': EditIcon,
  'external-link': ExternalLinkIcon,
  'eye': EyeIcon,
  'eye-off': EyeOffIcon,
  'file': FileIcon,
  'filter': FilterIcon,
  'folder': FolderIcon,
  'code': CodeIcon,
  'git-branch': GitBranchIcon,
  'globe': GlobeIcon,
  'heart': HeartIcon,
  'home': HomeIcon,
  'image': ImageIcon,
  'info': InfoIcon,
  'italic': ItalicIcon,
  'layout-grid': LayoutGridIcon,
  'list': ListIcon,
  'loader': LoaderIcon,
  'lock': LockIcon,
  'log-out': LogOutIcon,
  'mail': MailIcon,
  'menu': MenuIcon,
  'minus': MinusIcon,
  'monitor': MonitorIcon,
  'moon': MoonIcon,
  'more-horizontal': MoreHorizontalIcon,
  'package': PackageIcon,
  'palette': PaletteIcon,
  'plus': PlusIcon,
  'search': SearchIcon,
  'settings': SettingsIcon,
  'shopping-cart': ShoppingCartIcon,
  'smartphone': SmartphoneIcon,
  'star': StarIcon,
  'sun': SunIcon,
  'trash': TrashIcon,
  'trending-up': TrendingUpIcon,
  'underline': UnderlineIcon,
  'upload': UploadIcon,
  'user': UserIcon,
  'users': UsersIcon,
  'x': XIcon,
  'x-circle': XCircleIcon,
  'grip-horizontal': GripHorizontalIcon,
  'grip-vertical': GripVerticalIcon,
  'heading': HeadingIcon,
  'link': LinkIcon,
  'list-ordered': ListOrderedIcon,
  'pause': PauseIcon,
  'play': PlayIcon,
  'quote': QuoteIcon,
  'rotate-ccw': RotateCcwIcon,
  'rotate-cw': RotateCwIcon,
  'strikethrough': StrikethroughIcon,
  'volume': VolumeIcon,
  'volume-off': VolumeOffIcon,
} satisfies Record<string, IconComponent>
