// AUTO-GENERATED by scripts/generate-catalog.mjs — do not edit by hand.
import type { ComponentMeta } from './types'
import accordionMeta from '../components/accordion/accordion.meta'
import alertMeta from '../components/alert/alert.meta'
import alertDialogMeta from '../components/alert-dialog/alert-dialog.meta'
import appShellMeta from '../components/app-shell/app-shell.meta'
import aspectRatioMeta from '../components/aspect-ratio/aspect-ratio.meta'
import audioPlayerMeta from '../components/audio-player/audio-player.meta'
import autoGridMeta from '../components/layout/auto-grid.meta'
import autocompleteMeta from '../components/autocomplete/autocomplete.meta'
import avatarMeta from '../components/avatar/avatar.meta'
import badgeMeta from '../components/badge/badge.meta'
import breadcrumbMeta from '../components/breadcrumb/breadcrumb.meta'
import buttonMeta from '../components/button/button.meta'
import buttonGroupMeta from '../components/button-group/button-group.meta'
import calendarMeta from '../components/calendar/calendar.meta'
import cardMeta from '../components/card/card.meta'
import checkboxMeta from '../components/checkbox/checkbox.meta'
import chipMeta from '../components/chip/chip.meta'
import circularProgressMeta from '../components/circular-progress/circular-progress.meta'
import collapsibleMeta from '../components/collapsible/collapsible.meta'
import comboboxMeta from '../components/combobox/combobox.meta'
import commandPaletteMeta from '../components/command-palette/command-palette.meta'
import containerMeta from '../components/layout/container.meta'
import contextMenuMeta from '../components/context-menu/context-menu.meta'
import datePickerMeta from '../components/date-picker/date-picker.meta'
import dateRangePickerMeta from '../components/date-range-picker/date-range-picker.meta'
import dialogMeta from '../components/dialog/dialog.meta'
import drawerMeta from '../components/drawer/drawer.meta'
import dropdownMenuMeta from '../components/dropdown-menu/dropdown-menu.meta'
import emptyStateMeta from '../components/empty-state/empty-state.meta'
import errorStateMeta from '../components/error-state/error-state.meta'
import fabMeta from '../components/fab/fab.meta'
import fieldMeta from '../components/field/field.meta'
import fileDropzoneMeta from '../components/file-dropzone/file-dropzone.meta'
import fileUploadMeta from '../components/file-upload/file-upload.meta'
import formMeta from '../components/form/form.meta'
import gridMeta from '../components/layout/grid.meta'
import hoverCardMeta from '../components/hover-card/hover-card.meta'
import iconButtonMeta from '../components/icon-button/icon-button.meta'
import imageMeta from '../components/image/image.meta'
import imageGalleryMeta from '../components/image-gallery/image-gallery.meta'
import inputMeta from '../components/input/input.meta'
import labelMeta from '../components/label/label.meta'
import listMeta from '../components/list/list.meta'
import loadingButtonMeta from '../components/loading-button/loading-button.meta'
import menuMeta from '../components/menu/menu.meta'
import multiSelectMeta from '../components/multi-select/multi-select.meta'
import navigationBarMeta from '../components/navigation-bar/navigation-bar.meta'
import navigationMenuMeta from '../components/navigation-menu/navigation-menu.meta'
import numberInputMeta from '../components/number-input/number-input.meta'
import otpInputMeta from '../components/otp-input/otp-input.meta'
import paginationMeta from '../components/pagination/pagination.meta'
import passwordInputMeta from '../components/password-input/password-input.meta'
import popoverMeta from '../components/popover/popover.meta'
import progressMeta from '../components/progress/progress.meta'
import radioGroupMeta from '../components/radio-group/radio-group.meta'
import resizablePanelMeta from '../components/resizable-panel/resizable-panel.meta'
import scrollAreaMeta from '../components/scroll-area/scroll-area.meta'
import searchMeta from '../components/search/search.meta'
import sectionMeta from '../components/section/section.meta'
import selectMeta from '../components/select/select.meta'
import separatorMeta from '../components/separator/separator.meta'
import sheetMeta from '../components/sheet/sheet.meta'
import showHideMeta from '../components/show-hide/show-hide.meta'
import sidebarMeta from '../components/sidebar/sidebar.meta'
import skeletonMeta from '../components/skeleton/skeleton.meta'
import sliderMeta from '../components/slider/slider.meta'
import snackbarMeta from '../components/snackbar/snackbar.meta'
import spinnerMeta from '../components/spinner/spinner.meta'
import stackMeta from '../components/layout/stack.meta'
import stepperMeta from '../components/stepper/stepper.meta'
import stickyMeta from '../components/sticky/sticky.meta'
import switchMeta from '../components/switch/switch.meta'
import tabsMeta from '../components/tabs/tabs.meta'
import textareaMeta from '../components/textarea/textarea.meta'
import timePickerMeta from '../components/time-picker/time-picker.meta'
import toastMeta from '../components/toast/toast.meta'
import toggleMeta from '../components/toggle/toggle.meta'
import toggleGroupMeta from '../components/toggle-group/toggle-group.meta'
import tooltipMeta from '../components/tooltip/tooltip.meta'
import typographyMeta from '../components/typography/typography.meta'
import videoMeta from '../components/video/video.meta'
import wrapMeta from '../components/layout/wrap.meta'

/** The metadata of every @advui/core component, sorted by slug. */
export const components: ComponentMeta[] = [
  accordionMeta,
  alertMeta,
  alertDialogMeta,
  appShellMeta,
  aspectRatioMeta,
  audioPlayerMeta,
  autoGridMeta,
  autocompleteMeta,
  avatarMeta,
  badgeMeta,
  breadcrumbMeta,
  buttonMeta,
  buttonGroupMeta,
  calendarMeta,
  cardMeta,
  checkboxMeta,
  chipMeta,
  circularProgressMeta,
  collapsibleMeta,
  comboboxMeta,
  commandPaletteMeta,
  containerMeta,
  contextMenuMeta,
  datePickerMeta,
  dateRangePickerMeta,
  dialogMeta,
  drawerMeta,
  dropdownMenuMeta,
  emptyStateMeta,
  errorStateMeta,
  fabMeta,
  fieldMeta,
  fileDropzoneMeta,
  fileUploadMeta,
  formMeta,
  gridMeta,
  hoverCardMeta,
  iconButtonMeta,
  imageMeta,
  imageGalleryMeta,
  inputMeta,
  labelMeta,
  listMeta,
  loadingButtonMeta,
  menuMeta,
  multiSelectMeta,
  navigationBarMeta,
  navigationMenuMeta,
  numberInputMeta,
  otpInputMeta,
  paginationMeta,
  passwordInputMeta,
  popoverMeta,
  progressMeta,
  radioGroupMeta,
  resizablePanelMeta,
  scrollAreaMeta,
  searchMeta,
  sectionMeta,
  selectMeta,
  separatorMeta,
  sheetMeta,
  showHideMeta,
  sidebarMeta,
  skeletonMeta,
  sliderMeta,
  snackbarMeta,
  spinnerMeta,
  stackMeta,
  stepperMeta,
  stickyMeta,
  switchMeta,
  tabsMeta,
  textareaMeta,
  timePickerMeta,
  toastMeta,
  toggleMeta,
  toggleGroupMeta,
  tooltipMeta,
  typographyMeta,
  videoMeta,
  wrapMeta,
]
