// AUTO-GENERATED by scripts/generate-catalog.mjs — do not edit by hand.
import type { ComponentType } from 'react'
import AlertVariants from '../components/alert/examples/variants'
import AvatarBasic from '../components/avatar/examples/basic'
import AvatarSizes from '../components/avatar/examples/sizes'
import AvatarGroup from '../components/avatar/examples/group'
import BadgeVariants from '../components/badge/examples/variants'
import BadgeWithIcon from '../components/badge/examples/with-icon'
import ButtonBasic from '../components/button/examples/basic'
import ButtonVariants from '../components/button/examples/variants'
import ButtonSizes from '../components/button/examples/sizes'
import ButtonWithIcon from '../components/button/examples/with-icon'
import ButtonLoading from '../components/button/examples/loading'
import ButtonDisabled from '../components/button/examples/disabled'
import ButtonFullWidth from '../components/button/examples/full-width'
import CardBasic from '../components/card/examples/basic'
import CardVariants from '../components/card/examples/variants'
import CardInteractive from '../components/card/examples/interactive'
import CheckboxBasic from '../components/checkbox/examples/basic'
import CheckboxIndeterminate from '../components/checkbox/examples/indeterminate'
import ContainerContainer from '../components/layout/examples/container'
import DialogBasic from '../components/dialog/examples/basic'
import DialogConfirm from '../components/dialog/examples/confirm'
import GridGrid from '../components/layout/examples/grid'
import IconButtonBasic from '../components/icon-button/examples/basic'
import IconButtonVariants from '../components/icon-button/examples/variants'
import IconButtonSizes from '../components/icon-button/examples/sizes'
import InputBasic from '../components/input/examples/basic'
import InputSizes from '../components/input/examples/sizes'
import InputStates from '../components/input/examples/states'
import LabelBasic from '../components/label/examples/basic'
import ProgressBasic from '../components/progress/examples/basic'
import RadioGroupBasic from '../components/radio-group/examples/basic'
import SelectBasic from '../components/select/examples/basic'
import SelectGroups from '../components/select/examples/groups'
import SeparatorBasic from '../components/separator/examples/basic'
import SkeletonCard from '../components/skeleton/examples/card'
import SpinnerBasic from '../components/spinner/examples/basic'
import StackBasic from '../components/layout/examples/basic'
import StackResponsive from '../components/layout/examples/responsive'
import SwitchSettings from '../components/switch/examples/settings'
import TabsBasic from '../components/tabs/examples/basic'
import TabsUnderline from '../components/tabs/examples/underline'
import TextareaBasic from '../components/textarea/examples/basic'
import ToastTypes from '../components/toast/examples/types'
import ToastAction from '../components/toast/examples/action'
import TooltipBasic from '../components/tooltip/examples/basic'
import TypographyScale from '../components/typography/examples/scale'
import TypographyTones from '../components/typography/examples/tones'

export const examples: Record<string, Record<string, ComponentType>> = {
  'alert': {
    'variants': AlertVariants,
  },
  'avatar': {
    'basic': AvatarBasic,
    'sizes': AvatarSizes,
    'group': AvatarGroup,
  },
  'badge': {
    'variants': BadgeVariants,
    'with-icon': BadgeWithIcon,
  },
  'button': {
    'basic': ButtonBasic,
    'variants': ButtonVariants,
    'sizes': ButtonSizes,
    'with-icon': ButtonWithIcon,
    'loading': ButtonLoading,
    'disabled': ButtonDisabled,
    'full-width': ButtonFullWidth,
  },
  'card': {
    'basic': CardBasic,
    'variants': CardVariants,
    'interactive': CardInteractive,
  },
  'checkbox': {
    'basic': CheckboxBasic,
    'indeterminate': CheckboxIndeterminate,
  },
  'container': {
    'container': ContainerContainer,
  },
  'dialog': {
    'basic': DialogBasic,
    'confirm': DialogConfirm,
  },
  'grid': {
    'grid': GridGrid,
  },
  'icon-button': {
    'basic': IconButtonBasic,
    'variants': IconButtonVariants,
    'sizes': IconButtonSizes,
  },
  'input': {
    'basic': InputBasic,
    'sizes': InputSizes,
    'states': InputStates,
  },
  'label': {
    'basic': LabelBasic,
  },
  'progress': {
    'basic': ProgressBasic,
  },
  'radio-group': {
    'basic': RadioGroupBasic,
  },
  'select': {
    'basic': SelectBasic,
    'groups': SelectGroups,
  },
  'separator': {
    'basic': SeparatorBasic,
  },
  'skeleton': {
    'card': SkeletonCard,
  },
  'spinner': {
    'basic': SpinnerBasic,
  },
  'stack': {
    'basic': StackBasic,
    'responsive': StackResponsive,
  },
  'switch': {
    'settings': SwitchSettings,
  },
  'tabs': {
    'basic': TabsBasic,
    'underline': TabsUnderline,
  },
  'textarea': {
    'basic': TextareaBasic,
  },
  'toast': {
    'types': ToastTypes,
    'action': ToastAction,
  },
  'tooltip': {
    'basic': TooltipBasic,
  },
  'typography': {
    'scale': TypographyScale,
    'tones': TypographyTones,
  },
}
