// AUTO-GENERATED by scripts/generate-catalog.mjs — do not edit by hand.
import type { ComponentType } from 'react'
import AccordionBasic from '../components/accordion/examples/basic'
import AccordionCard from '../components/accordion/examples/card'
import AlertVariants from '../components/alert/examples/variants'
import AlertDialogBasic from '../components/alert-dialog/examples/basic'
import AlertDialogAsync from '../components/alert-dialog/examples/async'
import AspectRatioBasic from '../components/aspect-ratio/examples/basic'
import AspectRatioRatios from '../components/aspect-ratio/examples/ratios'
import AvatarBasic from '../components/avatar/examples/basic'
import AvatarSizes from '../components/avatar/examples/sizes'
import AvatarGroup from '../components/avatar/examples/group'
import BadgeVariants from '../components/badge/examples/variants'
import BadgeWithIcon from '../components/badge/examples/with-icon'
import BreadcrumbBasic from '../components/breadcrumb/examples/basic'
import BreadcrumbCollapsed from '../components/breadcrumb/examples/collapsed'
import ButtonBasic from '../components/button/examples/basic'
import ButtonVariants from '../components/button/examples/variants'
import ButtonSizes from '../components/button/examples/sizes'
import ButtonWithIcon from '../components/button/examples/with-icon'
import ButtonLoading from '../components/button/examples/loading'
import ButtonDisabled from '../components/button/examples/disabled'
import ButtonFullWidth from '../components/button/examples/full-width'
import ButtonGroupBasic from '../components/button-group/examples/basic'
import ButtonGroupSplit from '../components/button-group/examples/split'
import ButtonGroupOrientation from '../components/button-group/examples/orientation'
import CardBasic from '../components/card/examples/basic'
import CardVariants from '../components/card/examples/variants'
import CardInteractive from '../components/card/examples/interactive'
import CheckboxBasic from '../components/checkbox/examples/basic'
import CheckboxIndeterminate from '../components/checkbox/examples/indeterminate'
import ChipFilter from '../components/chip/examples/filter'
import ChipInput from '../components/chip/examples/input'
import CircularProgressBasic from '../components/circular-progress/examples/basic'
import CircularProgressSizes from '../components/circular-progress/examples/sizes'
import CollapsibleBasic from '../components/collapsible/examples/basic'
import CollapsibleSettings from '../components/collapsible/examples/settings'
import ContainerContainer from '../components/layout/examples/container'
import DialogBasic from '../components/dialog/examples/basic'
import DialogConfirm from '../components/dialog/examples/confirm'
import DropdownMenuBasic from '../components/dropdown-menu/examples/basic'
import DropdownMenuOptions from '../components/dropdown-menu/examples/options'
import FabBasic from '../components/fab/examples/basic'
import FabExtended from '../components/fab/examples/extended'
import GridGrid from '../components/layout/examples/grid'
import IconButtonBasic from '../components/icon-button/examples/basic'
import IconButtonVariants from '../components/icon-button/examples/variants'
import IconButtonSizes from '../components/icon-button/examples/sizes'
import InputBasic from '../components/input/examples/basic'
import InputSizes from '../components/input/examples/sizes'
import InputStates from '../components/input/examples/states'
import LabelBasic from '../components/label/examples/basic'
import NavigationBarBasic from '../components/navigation-bar/examples/basic'
import PopoverBasic from '../components/popover/examples/basic'
import PopoverFilter from '../components/popover/examples/filter'
import ProgressBasic from '../components/progress/examples/basic'
import RadioGroupBasic from '../components/radio-group/examples/basic'
import ScrollAreaBasic from '../components/scroll-area/examples/basic'
import ScrollAreaHorizontal from '../components/scroll-area/examples/horizontal'
import SelectBasic from '../components/select/examples/basic'
import SelectGroups from '../components/select/examples/groups'
import SeparatorBasic from '../components/separator/examples/basic'
import SheetBasic from '../components/sheet/examples/basic'
import SheetScroll from '../components/sheet/examples/scroll'
import SkeletonCard from '../components/skeleton/examples/card'
import SliderBasic from '../components/slider/examples/basic'
import SliderRange from '../components/slider/examples/range'
import SnackbarBasic from '../components/snackbar/examples/basic'
import SnackbarPersistent from '../components/snackbar/examples/persistent'
import SpinnerBasic from '../components/spinner/examples/basic'
import StackBasic from '../components/layout/examples/basic'
import StackResponsive from '../components/layout/examples/responsive'
import SwitchSettings from '../components/switch/examples/settings'
import TabsBasic from '../components/tabs/examples/basic'
import TabsUnderline from '../components/tabs/examples/underline'
import TextareaBasic from '../components/textarea/examples/basic'
import ToastTypes from '../components/toast/examples/types'
import ToastAction from '../components/toast/examples/action'
import ToggleBasic from '../components/toggle/examples/basic'
import ToggleControlled from '../components/toggle/examples/controlled'
import ToggleGroupBasic from '../components/toggle-group/examples/basic'
import ToggleGroupMultiple from '../components/toggle-group/examples/multiple'
import TooltipBasic from '../components/tooltip/examples/basic'
import TypographyScale from '../components/typography/examples/scale'
import TypographyTones from '../components/typography/examples/tones'

export const examples: Record<string, Record<string, ComponentType>> = {
  'accordion': {
    'basic': AccordionBasic,
    'card': AccordionCard,
  },
  'alert': {
    'variants': AlertVariants,
  },
  'alert-dialog': {
    'basic': AlertDialogBasic,
    'async': AlertDialogAsync,
  },
  'aspect-ratio': {
    'basic': AspectRatioBasic,
    'ratios': AspectRatioRatios,
  },
  'avatar': {
    'basic': AvatarBasic,
    'sizes': AvatarSizes,
    'group': AvatarGroup,
  },
  'badge': {
    'variants': BadgeVariants,
    'with-icon': BadgeWithIcon,
  },
  'breadcrumb': {
    'basic': BreadcrumbBasic,
    'collapsed': BreadcrumbCollapsed,
  },
  'button': {
    'basic': ButtonBasic,
    'variants': ButtonVariants,
    'sizes': ButtonSizes,
    'with-icon': ButtonWithIcon,
    'loading': ButtonLoading,
    'disabled': ButtonDisabled,
    'full-width': ButtonFullWidth,
  },
  'button-group': {
    'basic': ButtonGroupBasic,
    'split': ButtonGroupSplit,
    'orientation': ButtonGroupOrientation,
  },
  'card': {
    'basic': CardBasic,
    'variants': CardVariants,
    'interactive': CardInteractive,
  },
  'checkbox': {
    'basic': CheckboxBasic,
    'indeterminate': CheckboxIndeterminate,
  },
  'chip': {
    'filter': ChipFilter,
    'input': ChipInput,
  },
  'circular-progress': {
    'basic': CircularProgressBasic,
    'sizes': CircularProgressSizes,
  },
  'collapsible': {
    'basic': CollapsibleBasic,
    'settings': CollapsibleSettings,
  },
  'container': {
    'container': ContainerContainer,
  },
  'dialog': {
    'basic': DialogBasic,
    'confirm': DialogConfirm,
  },
  'dropdown-menu': {
    'basic': DropdownMenuBasic,
    'options': DropdownMenuOptions,
  },
  'fab': {
    'basic': FabBasic,
    'extended': FabExtended,
  },
  'grid': {
    'grid': GridGrid,
  },
  'icon-button': {
    'basic': IconButtonBasic,
    'variants': IconButtonVariants,
    'sizes': IconButtonSizes,
  },
  'input': {
    'basic': InputBasic,
    'sizes': InputSizes,
    'states': InputStates,
  },
  'label': {
    'basic': LabelBasic,
  },
  'navigation-bar': {
    'basic': NavigationBarBasic,
  },
  'popover': {
    'basic': PopoverBasic,
    'filter': PopoverFilter,
  },
  'progress': {
    'basic': ProgressBasic,
  },
  'radio-group': {
    'basic': RadioGroupBasic,
  },
  'scroll-area': {
    'basic': ScrollAreaBasic,
    'horizontal': ScrollAreaHorizontal,
  },
  'select': {
    'basic': SelectBasic,
    'groups': SelectGroups,
  },
  'separator': {
    'basic': SeparatorBasic,
  },
  'sheet': {
    'basic': SheetBasic,
    'scroll': SheetScroll,
  },
  'skeleton': {
    'card': SkeletonCard,
  },
  'slider': {
    'basic': SliderBasic,
    'range': SliderRange,
  },
  'snackbar': {
    'basic': SnackbarBasic,
    'persistent': SnackbarPersistent,
  },
  'spinner': {
    'basic': SpinnerBasic,
  },
  'stack': {
    'basic': StackBasic,
    'responsive': StackResponsive,
  },
  'switch': {
    'settings': SwitchSettings,
  },
  'tabs': {
    'basic': TabsBasic,
    'underline': TabsUnderline,
  },
  'textarea': {
    'basic': TextareaBasic,
  },
  'toast': {
    'types': ToastTypes,
    'action': ToastAction,
  },
  'toggle': {
    'basic': ToggleBasic,
    'controlled': ToggleControlled,
  },
  'toggle-group': {
    'basic': ToggleGroupBasic,
    'multiple': ToggleGroupMultiple,
  },
  'tooltip': {
    'basic': TooltipBasic,
  },
  'typography': {
    'scale': TypographyScale,
    'tones': TypographyTones,
  },
}
