// AUTO-GENERATED by scripts/generate-catalog.mjs — do not edit by hand.
import accordionMeta from '../components/accordion/accordion.meta'
import alertMeta from '../components/alert/alert.meta'
import alertDialogMeta from '../components/alert-dialog/alert-dialog.meta'
import avatarMeta from '../components/avatar/avatar.meta'
import badgeMeta from '../components/badge/badge.meta'
import breadcrumbMeta from '../components/breadcrumb/breadcrumb.meta'
import buttonMeta from '../components/button/button.meta'
import cardMeta from '../components/card/card.meta'
import checkboxMeta from '../components/checkbox/checkbox.meta'
import chipMeta from '../components/chip/chip.meta'
import containerMeta from '../components/layout/container.meta'
import dialogMeta from '../components/dialog/dialog.meta'
import dropdownMenuMeta from '../components/dropdown-menu/dropdown-menu.meta'
import fabMeta from '../components/fab/fab.meta'
import gridMeta from '../components/layout/grid.meta'
import iconButtonMeta from '../components/icon-button/icon-button.meta'
import inputMeta from '../components/input/input.meta'
import labelMeta from '../components/label/label.meta'
import navigationBarMeta from '../components/navigation-bar/navigation-bar.meta'
import popoverMeta from '../components/popover/popover.meta'
import progressMeta from '../components/progress/progress.meta'
import radioGroupMeta from '../components/radio-group/radio-group.meta'
import selectMeta from '../components/select/select.meta'
import separatorMeta from '../components/separator/separator.meta'
import sheetMeta from '../components/sheet/sheet.meta'
import skeletonMeta from '../components/skeleton/skeleton.meta'
import sliderMeta from '../components/slider/slider.meta'
import snackbarMeta from '../components/snackbar/snackbar.meta'
import spinnerMeta from '../components/spinner/spinner.meta'
import stackMeta from '../components/layout/stack.meta'
import switchMeta from '../components/switch/switch.meta'
import tabsMeta from '../components/tabs/tabs.meta'
import textareaMeta from '../components/textarea/textarea.meta'
import toastMeta from '../components/toast/toast.meta'
import toggleMeta from '../components/toggle/toggle.meta'
import toggleGroupMeta from '../components/toggle-group/toggle-group.meta'
import tooltipMeta from '../components/tooltip/tooltip.meta'
import typographyMeta from '../components/typography/typography.meta'
import type { ComponentMeta } from './types'

export const components: ComponentMeta[] = [
  accordionMeta,
  alertMeta,
  alertDialogMeta,
  avatarMeta,
  badgeMeta,
  breadcrumbMeta,
  buttonMeta,
  cardMeta,
  checkboxMeta,
  chipMeta,
  containerMeta,
  dialogMeta,
  dropdownMenuMeta,
  fabMeta,
  gridMeta,
  iconButtonMeta,
  inputMeta,
  labelMeta,
  navigationBarMeta,
  popoverMeta,
  progressMeta,
  radioGroupMeta,
  selectMeta,
  separatorMeta,
  sheetMeta,
  skeletonMeta,
  sliderMeta,
  snackbarMeta,
  spinnerMeta,
  stackMeta,
  switchMeta,
  tabsMeta,
  textareaMeta,
  toastMeta,
  toggleMeta,
  toggleGroupMeta,
  tooltipMeta,
  typographyMeta,
]

export function getComponent(slug: string): ComponentMeta | undefined {
  return components.find((component) => component.slug === slug)
}

export { roadmap, type RoadmapItem } from './roadmap'
export { categories, defineMeta } from './types'
export type * from './types'
