// AUTO-GENERATED by scripts/generate-catalog.mjs — do not edit by hand.
import accordionMeta from '../components/accordion/accordion.meta'
import alertMeta from '../components/alert/alert.meta'
import avatarMeta from '../components/avatar/avatar.meta'
import badgeMeta from '../components/badge/badge.meta'
import buttonMeta from '../components/button/button.meta'
import cardMeta from '../components/card/card.meta'
import checkboxMeta from '../components/checkbox/checkbox.meta'
import containerMeta from '../components/layout/container.meta'
import dialogMeta from '../components/dialog/dialog.meta'
import dropdownMenuMeta from '../components/dropdown-menu/dropdown-menu.meta'
import gridMeta from '../components/layout/grid.meta'
import iconButtonMeta from '../components/icon-button/icon-button.meta'
import inputMeta from '../components/input/input.meta'
import labelMeta from '../components/label/label.meta'
import popoverMeta from '../components/popover/popover.meta'
import progressMeta from '../components/progress/progress.meta'
import radioGroupMeta from '../components/radio-group/radio-group.meta'
import selectMeta from '../components/select/select.meta'
import separatorMeta from '../components/separator/separator.meta'
import skeletonMeta from '../components/skeleton/skeleton.meta'
import sliderMeta from '../components/slider/slider.meta'
import spinnerMeta from '../components/spinner/spinner.meta'
import stackMeta from '../components/layout/stack.meta'
import switchMeta from '../components/switch/switch.meta'
import tabsMeta from '../components/tabs/tabs.meta'
import textareaMeta from '../components/textarea/textarea.meta'
import toastMeta from '../components/toast/toast.meta'
import tooltipMeta from '../components/tooltip/tooltip.meta'
import typographyMeta from '../components/typography/typography.meta'
import type { ComponentMeta } from './types'

export const components: ComponentMeta[] = [
  accordionMeta,
  alertMeta,
  avatarMeta,
  badgeMeta,
  buttonMeta,
  cardMeta,
  checkboxMeta,
  containerMeta,
  dialogMeta,
  dropdownMenuMeta,
  gridMeta,
  iconButtonMeta,
  inputMeta,
  labelMeta,
  popoverMeta,
  progressMeta,
  radioGroupMeta,
  selectMeta,
  separatorMeta,
  skeletonMeta,
  sliderMeta,
  spinnerMeta,
  stackMeta,
  switchMeta,
  tabsMeta,
  textareaMeta,
  toastMeta,
  tooltipMeta,
  typographyMeta,
]

export function getComponent(slug: string): ComponentMeta | undefined {
  return components.find((component) => component.slug === slug)
}

export { roadmap, type RoadmapItem } from './roadmap'
export { categories, defineMeta } from './types'
export type * from './types'
