// AUTO-GENERATED by scripts/generate-catalog.mjs — do not edit by hand.
import accordionMeta from '../components/accordion/accordion.meta'
import alertMeta from '../components/alert/alert.meta'
import alertDialogMeta from '../components/alert-dialog/alert-dialog.meta'
import aspectRatioMeta from '../components/aspect-ratio/aspect-ratio.meta'
import avatarMeta from '../components/avatar/avatar.meta'
import badgeMeta from '../components/badge/badge.meta'
import breadcrumbMeta from '../components/breadcrumb/breadcrumb.meta'
import buttonMeta from '../components/button/button.meta'
import buttonGroupMeta from '../components/button-group/button-group.meta'
import calendarMeta from '../components/calendar/calendar.meta'
import cardMeta from '../components/card/card.meta'
import checkboxMeta from '../components/checkbox/checkbox.meta'
import chipMeta from '../components/chip/chip.meta'
import circularProgressMeta from '../components/circular-progress/circular-progress.meta'
import collapsibleMeta from '../components/collapsible/collapsible.meta'
import containerMeta from '../components/layout/container.meta'
import contextMenuMeta from '../components/context-menu/context-menu.meta'
import datePickerMeta from '../components/date-picker/date-picker.meta'
import dateRangePickerMeta from '../components/date-range-picker/date-range-picker.meta'
import dialogMeta from '../components/dialog/dialog.meta'
import drawerMeta from '../components/drawer/drawer.meta'
import dropdownMenuMeta from '../components/dropdown-menu/dropdown-menu.meta'
import emptyStateMeta from '../components/empty-state/empty-state.meta'
import errorStateMeta from '../components/error-state/error-state.meta'
import fabMeta from '../components/fab/fab.meta'
import formFieldMeta from '../components/form-field/form-field.meta'
import gridMeta from '../components/layout/grid.meta'
import hoverCardMeta from '../components/hover-card/hover-card.meta'
import iconButtonMeta from '../components/icon-button/icon-button.meta'
import inputMeta from '../components/input/input.meta'
import labelMeta from '../components/label/label.meta'
import menuMeta from '../components/menu/menu.meta'
import navigationBarMeta from '../components/navigation-bar/navigation-bar.meta'
import numberInputMeta from '../components/number-input/number-input.meta'
import otpInputMeta from '../components/otp-input/otp-input.meta'
import passwordInputMeta from '../components/password-input/password-input.meta'
import popoverMeta from '../components/popover/popover.meta'
import progressMeta from '../components/progress/progress.meta'
import radioGroupMeta from '../components/radio-group/radio-group.meta'
import scrollAreaMeta from '../components/scroll-area/scroll-area.meta'
import selectMeta from '../components/select/select.meta'
import separatorMeta from '../components/separator/separator.meta'
import sheetMeta from '../components/sheet/sheet.meta'
import skeletonMeta from '../components/skeleton/skeleton.meta'
import sliderMeta from '../components/slider/slider.meta'
import snackbarMeta from '../components/snackbar/snackbar.meta'
import spinnerMeta from '../components/spinner/spinner.meta'
import stackMeta from '../components/layout/stack.meta'
import switchMeta from '../components/switch/switch.meta'
import tabsMeta from '../components/tabs/tabs.meta'
import textareaMeta from '../components/textarea/textarea.meta'
import timePickerMeta from '../components/time-picker/time-picker.meta'
import toastMeta from '../components/toast/toast.meta'
import toggleMeta from '../components/toggle/toggle.meta'
import toggleGroupMeta from '../components/toggle-group/toggle-group.meta'
import tooltipMeta from '../components/tooltip/tooltip.meta'
import typographyMeta from '../components/typography/typography.meta'
import type { ComponentMeta } from './types'

export const components: ComponentMeta[] = [
  accordionMeta,
  alertMeta,
  alertDialogMeta,
  aspectRatioMeta,
  avatarMeta,
  badgeMeta,
  breadcrumbMeta,
  buttonMeta,
  buttonGroupMeta,
  calendarMeta,
  cardMeta,
  checkboxMeta,
  chipMeta,
  circularProgressMeta,
  collapsibleMeta,
  containerMeta,
  contextMenuMeta,
  datePickerMeta,
  dateRangePickerMeta,
  dialogMeta,
  drawerMeta,
  dropdownMenuMeta,
  emptyStateMeta,
  errorStateMeta,
  fabMeta,
  formFieldMeta,
  gridMeta,
  hoverCardMeta,
  iconButtonMeta,
  inputMeta,
  labelMeta,
  menuMeta,
  navigationBarMeta,
  numberInputMeta,
  otpInputMeta,
  passwordInputMeta,
  popoverMeta,
  progressMeta,
  radioGroupMeta,
  scrollAreaMeta,
  selectMeta,
  separatorMeta,
  sheetMeta,
  skeletonMeta,
  sliderMeta,
  snackbarMeta,
  spinnerMeta,
  stackMeta,
  switchMeta,
  tabsMeta,
  textareaMeta,
  timePickerMeta,
  toastMeta,
  toggleMeta,
  toggleGroupMeta,
  tooltipMeta,
  typographyMeta,
]

export function getComponent(slug: string): ComponentMeta | undefined {
  return components.find((component) => component.slug === slug)
}

export { roadmap, type RoadmapItem } from './roadmap'
export { categories, defineMeta } from './types'
export type * from './types'
