// Generates src/generated.ts from the `lucide` package (ISC license).
// Only the curated list below is emitted so the default set stays small.
// Usage: pnpm --filter @advui/icons generate
import { writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import * as lucide from 'lucide'

export const ICON_NAMES = [
  'alert-circle',
  'alert-triangle',
  'align-center',
  'align-left',
  'align-right',
  'arrow-left',
  'arrow-right',
  'bar-chart',
  'bell',
  'bold',
  'calendar',
  'check',
  'check-circle',
  'chevron-down',
  'chevron-left',
  'chevron-right',
  'chevron-up',
  'chevrons-up-down',
  'circle',
  'copy',
  'credit-card',
  'download',
  'edit',
  'external-link',
  'eye',
  'eye-off',
  'file',
  'filter',
  'folder',
  'code',
  'git-branch',
  'globe',
  'heart',
  'home',
  'image',
  'info',
  'italic',
  'layout-grid',
  'list',
  'loader',
  'lock',
  'log-out',
  'mail',
  'menu',
  'minus',
  'monitor',
  'moon',
  'more-horizontal',
  'package',
  'palette',
  'plus',
  'search',
  'settings',
  'shopping-cart',
  'smartphone',
  'star',
  'sun',
  'trash',
  'trending-up',
  'underline',
  'upload',
  'user',
  'users',
  'x',
  'x-circle',
  'grip-horizontal',
  'grip-vertical',
  'heading',
  'link',
  'list-ordered',
  'pause',
  'play',
  'quote',
  'rotate-ccw',
  'rotate-cw',
  'strikethrough',
  'volume',
  'volume-off',
]

// Lucide renamed a few icons over time; accept either spelling.
const ALIASES = {
  'alert-circle': ['CircleAlert', 'AlertCircle'],
  'alert-triangle': ['TriangleAlert', 'AlertTriangle'],
  'align-center': ['TextAlignCenter', 'AlignCenter'],
  'align-left': ['TextAlignStart', 'AlignLeft'],
  'align-right': ['TextAlignEnd', 'AlignRight'],
  'bar-chart': ['ChartColumn', 'BarChart3', 'ChartBar', 'BarChart'],
  'check-circle': ['CircleCheck', 'CheckCircle'],
  edit: ['Pencil', 'Edit'],

  home: ['House', 'Home'],
  'more-horizontal': ['Ellipsis', 'MoreHorizontal'],
  trash: ['Trash2', 'Trash'],
  'x-circle': ['CircleX', 'XCircle'],
  loader: ['LoaderCircle', 'Loader2', 'Loader'],
  volume: ['Volume2'],
  'volume-off': ['VolumeX', 'VolumeOff'],
}

const pascal = (name) =>
  name
    .split('-')
    .map((part) => part[0].toUpperCase() + part.slice(1))
    .join('')

const source = lucide.icons ?? lucide
const lines = [
  '// AUTO-GENERATED by scripts/generate-icons.mjs from `lucide` (ISC). Do not edit.',
  "import type { IconNode } from './types'",
  '',
]
const missing = []

for (const name of ICON_NAMES) {
  const candidates = ALIASES[name] ?? [pascal(name)]
  const key = candidates.find((candidate) => Array.isArray(source[candidate]))
  if (!key) {
    missing.push(name)
    continue
  }
  const node = source[key].map((entry) => [entry[0], entry[1]])
  lines.push(
    `export const ${pascal(name).replace(/^./, (c) => c.toLowerCase())}Node: IconNode = ${JSON.stringify(node)}`,
  )
}

lines.push('')
lines.push(
  `export const iconNames = ${JSON.stringify(ICON_NAMES.filter((n) => !missing.includes(n)))} as const`,
)
lines.push('export type IconName = (typeof iconNames)[number]')
lines.push('')

if (missing.length) {
  console.error(`Missing icons in lucide: ${missing.join(', ')}`)
  process.exit(1)
}

const camel = (name) => pascal(name).replace(/^./, (c) => c.toLowerCase())
const components = [
  '// AUTO-GENERATED by scripts/generate-icons.mjs. Do not edit.',
  "import { createIcon } from './createIcon'",
  `import { ${ICON_NAMES.map((n) => `${camel(n)}Node`).join(', ')} } from './generated'`,
  "import type { IconComponent } from './types'",
  '',
  ...ICON_NAMES.map(
    (n) => `export const ${pascal(n)}Icon = /* @__PURE__ */ createIcon('${n}', ${camel(n)}Node)`,
  ),
  '',
  '/** Every built-in icon keyed by name — used by `<Icon name="…" />`. */',
  'export const defaultIcons = {',
  ...ICON_NAMES.map((n) => `  '${n}': ${pascal(n)}Icon,`),
  '} satisfies Record<string, IconComponent>',
  '',
]

const srcDir = join(dirname(fileURLToPath(import.meta.url)), '..', 'src')
writeFileSync(join(srcDir, 'generated.ts'), lines.join('\n'))
writeFileSync(join(srcDir, 'icons.ts'), components.join('\n'))
console.log(`Wrote ${ICON_NAMES.length} icons to ${srcDir}`)
