#!/usr/bin/env node
// Validates component metadata and generates:
//   packages/ui/src/meta/index.ts     – typed list of all component metadata
//   packages/ui/src/meta/examples.ts  – example components keyed by slug + example name
// Run: pnpm catalog   (also runs automatically before docs dev/build)
import { writeFileSync } from 'node:fs'
import { join, relative } from 'node:path'
import { loadCatalog, pascal, toPosix, uiSrc, validateCatalog } from './lib/catalog.mjs'

const entries = loadCatalog()
const problems = validateCatalog(entries)
if (problems.length) {
  console.error(`Catalog has ${problems.length} problem(s):\n  - ${problems.join('\n  - ')}`)
  process.exit(1)
}

const metaDir = join(uiSrc, 'meta')
const importPath = (file) => toPosix(relative(metaDir, file)).replace(/\.tsx?$/, '')
const header = '// AUTO-GENERATED by scripts/generate-catalog.mjs — do not edit by hand.\n'
const sorted = [...entries].sort((a, b) => a.meta.name.localeCompare(b.meta.name))

const metaImports = sorted.map(
  ({ meta, file }) => `import ${camel(meta.slug)}Meta from '${importPath(file)}'`,
)
const metaIndex = `${header}${metaImports.join('\n')}
import type { ComponentMeta } from './types'

export const components: ComponentMeta[] = [
${sorted.map(({ meta }) => `  ${camel(meta.slug)}Meta,`).join('\n')}
]

export function getComponent(slug: string): ComponentMeta | undefined {
  return components.find((component) => component.slug === slug)
}

export { roadmap, type RoadmapItem } from './roadmap'
export { categories, defineMeta } from './types'
export type * from './types'
`

const exampleImports = []
const exampleMap = []
for (const { meta, dir } of sorted) {
  const items = []
  for (const example of meta.examples) {
    const id = `${pascal(meta.slug)}${pascal(example.name)}`
    exampleImports.push(`import ${id} from '../components/${dir}/examples/${example.name}'`)
    items.push(`    '${example.name}': ${id},`)
  }
  exampleMap.push(`  '${meta.slug}': {\n${items.join('\n')}\n  },`)
}
const examplesIndex = `${header}import type { ComponentType } from 'react'
${exampleImports.join('\n')}

export const examples: Record<string, Record<string, ComponentType>> = {
${exampleMap.join('\n')}
}
`

writeFileSync(join(metaDir, 'index.ts'), metaIndex)
writeFileSync(join(metaDir, 'examples.ts'), examplesIndex)
const exampleCount = sorted.reduce((sum, { meta }) => sum + meta.examples.length, 0)
console.log(`Catalog OK: ${sorted.length} components, ${exampleCount} examples.`)

function camel(slug) {
  const p = pascal(slug)
  return p[0].toLowerCase() + p.slice(1)
}
