#!/usr/bin/env node
// Validates component metadata and generates, for every component package:
//   packages/catalog/src/index.ts     – typed list of all component metadata, with its package
//   packages/catalog/src/examples.ts  – example components keyed by slug + example name
// Run: pnpm catalog   (also runs automatically before docs dev/build)
import { writeFileSync } from 'node:fs'
import { join, relative } from 'node:path'
import {
  catalogSrc,
  componentPackages,
  corePackage,
  loadCatalog,
  pascal,
  toPosix,
  validateCatalog,
} from './lib/catalog.mjs'

const entries = loadCatalog()
const problems = validateCatalog(entries)
if (problems.length) {
  console.error(`Catalog has ${problems.length} problem(s):\n  - ${problems.join('\n  - ')}`)
  process.exit(1)
}

const importPath = (file) => toPosix(relative(catalogSrc, file)).replace(/\.tsx?$/, '')
const header = '// AUTO-GENERATED by scripts/generate-catalog.mjs — do not edit by hand.\n'
const sorted = [...entries].sort((a, b) => a.meta.name.localeCompare(b.meta.name))

const metaImports = sorted.map(
  ({ meta, file }) => `import ${camel(meta.slug)}Meta from '${importPath(file)}'`,
)
const packageList = componentPackages.map(({ name, description, dir }) => ({
  name,
  // `@advui/data` → "Data"
  title: name
    .split('/')
    .pop()
    .replace(/^./, (c) => c.toUpperCase()),
  description,
  dir,
}))

const metaIndex = `${header}${metaImports.join('\n')}
import type { CatalogComponent, ComponentPackage } from './types'

/** Published component packages, in dependency order. */
export const packages: ComponentPackage[] = [
${packageList
  .map((p) =>
    [
      '  {',
      ...Object.entries(p).map(([key, value]) => `    ${key}: ${quote(value)},`),
      '  },',
    ].join('\n'),
  )
  .join('\n')}
]

export const components: CatalogComponent[] = [
${sorted.map(({ pkg, meta }) => `  { ...${camel(meta.slug)}Meta, package: '${pkg.name}' },`).join('\n')}
]

export function getComponent(slug: string): CatalogComponent | undefined {
  return components.find((component) => component.slug === slug)
}

export { roadmap, type RoadmapItem } from './roadmap'
export type { CatalogComponent, ComponentPackage } from './types'
export { categories, defineMeta } from '${corePackage.name}/meta'
export type * from '${corePackage.name}/meta'
`

const exampleImports = []
const exampleMap = []
for (const { pkg, meta, dir } of sorted) {
  const items = []
  for (const example of meta.examples) {
    const id = `${pascal(meta.slug)}${pascal(example.name)}`
    const file = join(pkg.componentsDir, dir, 'examples', example.name)
    exampleImports.push(`import ${id} from '${importPath(file)}'`)
    items.push(`    '${example.name}': ${id},`)
  }
  exampleMap.push(`  '${meta.slug}': {\n${items.join('\n')}\n  },`)
}
const examplesIndex = `${header}import type { ComponentType } from 'react'
${exampleImports.join('\n')}

export const examples: Record<string, Record<string, ComponentType>> = {
${exampleMap.join('\n')}
}
`

writeFileSync(join(catalogSrc, 'index.ts'), metaIndex)
writeFileSync(join(catalogSrc, 'examples.ts'), examplesIndex)
const exampleCount = sorted.reduce((sum, { meta }) => sum + meta.examples.length, 0)
console.log(`Catalog OK: ${sorted.length} components, ${exampleCount} examples.`)

function quote(value) {
  return `'${String(value).replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`
}

function camel(slug) {
  const p = pascal(slug)
  return p[0].toLowerCase() + p.slice(1)
}
