// AUTO-GENERATED by scripts/generate-catalog.mjs — do not edit by hand.
import type { ComponentMeta } from '@advui/core/meta'
import areaChartMeta from '../components/area-chart/area-chart.meta'
import barChartMeta from '../components/bar-chart/bar-chart.meta'
import lineChartMeta from '../components/line-chart/line-chart.meta'
import pieChartMeta from '../components/pie-chart/pie-chart.meta'

/** The metadata of every @advui/charts component, sorted by slug. */
export const components: ComponentMeta[] = [
  areaChartMeta,
  barChartMeta,
  lineChartMeta,
  pieChartMeta,
]
