// AUTO-GENERATED by scripts/generate-catalog.mjs — do not edit by hand.
import type { ComponentMeta } from '@advui/core/meta'
import dataGridMeta from '../components/data-grid/data-grid.meta'
import dataTableMeta from '../components/data-table/data-table.meta'
import kpiCardMeta from '../components/kpi-card/kpi-card.meta'
import statMeta from '../components/stat/stat.meta'
import tableMeta from '../components/table/table.meta'
import timelineMeta from '../components/timeline/timeline.meta'
import treeViewMeta from '../components/tree-view/tree-view.meta'

/** The metadata of every @advui/data component, sorted by slug. */
export const components: ComponentMeta[] = [
  dataGridMeta,
  dataTableMeta,
  kpiCardMeta,
  statMeta,
  tableMeta,
  timelineMeta,
  treeViewMeta,
]
